export const projects = [
  {
    title: 'VKG | Video',
    description:"VKG | Video is an Web-App which allows user to video chat directly.This Web-App Web RTC for the Video Calling and It's simple to use you just have to allow camera and microphone permission and keep your name it'll genrate a unique id and you can send this id to whom you wanna video chat directly it elimanites the privacy risk in today's mighty world.",
    image: '/images/VKG-Video.png',
    tags: ['React', 'Express','Socket.io'],
    source: 'https://vkg-video-app.netlify.app/',
    visit: 'https://vkg-video-app.netlify.app/',
    id: 0,
  },
  {
    title: 'VKG | Music',
    description: "VKG | Music is an simple web app which allows user to listen to the Ad-free music dirctly from YouTube API . You just have to search your favourite music there and it'll show you the four audio card in result from where you can Listen to your Music seamlessly.Furthermore you have controls on audio as well through which you can mange the playback speed , download option e.t.c",
      image: '/images/VKG-MUSIC.png',
      tags: ['YouTube API', 'Javascript', 'HTML/CSS'],
    source: 'https://github.com/VikasKrGond/Music-VKG/tree/main',
    visit: 'https://vikaskrgond.github.io/Music-VKG/',
    id: 1,
  },
  {
    title: 'VKG | YT Downloader',
    description:"VKG | YT Downloader is an Web-App which allows user to Download as well as LiveStream Videos in 360p & 720p respectively effortlessly directly from YouTube itself , Moreover you can also download and listen to the high Quality Audio as well.You just have to search and it'll pop 4 most relevant and matching result of  your search query.",
    image: '/images/VKG-YT_600x360.png',
    tags: ['React', 'JavaScript'],
    source: 'https://github.com/VikasKrGond/VKG-YT-Video',
    visit: 'https://vikaskrgond.github.io/VKG-YT-Video/',
    id: 2,
  },
  {
    title: 'VKG | Portfolio',
    description: "VKG Portfolio is my official portfolio to showcase my skills , projects .You can even know about me in depth via this portfolio cum digital resume.This Web App is developed in NextJS and React Styled Components.",
      image: '/images/VKG-Portfolio.png',
      tags: ['NextJS', 'React Style Components'],
    source: '#',
    visit: 'vikaskumargond.ml',
    id: 3,
  },
  {
    title: 'VKG | News',
    description: "VKG | News is a simple Web App in which visitor can have Trending News as Well as Trending Cricket news at the same time. Visitor can also search the article of it's choice directly and can view the full orignal page as well just by one click",
    image: '/images/VKG-News.png',
    tags: ['React', 'Javascript', 'News API'],
    source: 'https://github.com/VikasKrGond/VKG-News',
    visit: 'https://vikaskrgond.github.io/VKG-News/',
    id: 4,
  },
];

export const TimeLineData = [
  { year: 2019, text: 'Started my journey, Completed 10+2', },
  { year: 2020, text: 'Got Admisson in NIT Patna Btech CSE', },
  { year: 2021, text: 'Learnt MERN and React Native', },
  { year: 2021, text: 'Completed 500+ GitHub contributions', },
  { year: 2022, text: 'Converting Dreams to Accomplishments', },
];
